export const LIMIT = 20;
export const RESET = "RESET";

//* user.js
export const USER = {
	INITIAL: "USER.INITIAL",
	SUCCESS: "USER.SUCCESS",
	FAILED: "USER.FAILED",
	RESET: "USER.RESET",
	SETTING: "USER.SETTING",
	DIAMONDS_PLAN: "USER.DIAMONDS_PLAN",
	LEVEL: "USER.LEVEL",
	COMPLAINS: "USER.COMPLAINS",
	STICKER: "USER.STICKER",
	FANS: {
		INITIAL: "USER.FANS.INITIAL",
		SUCCESS: "USER.FANS.SUCCESS",
		FAILED: "USER.FANS.FAILED"
	},
	FOLLOWING: {
		INITIAL: "USER.FOLLOWING.INITIAL",
		SUCCESS: "USER.FOLLOWING.SUCCESS",
		FAILED: "USER.FOLLOWING.FAILED"
	},
	USER_PROFILE: {
		INITIAL: "USER.USER_PROFILE.INITIAL",
		SUCCESS: "USER.USER_PROFILE.SUCCESS",
		FAILED: "USER.USER_PROFILE.FAILED"
	},
	POSTS: {
		INITIAL: "USER.POSTS.INITIAL",
		SUCCESS: "USER.POSTS.SUCCESS",
		FAILED: "USER.POSTS.FAILED"
	},
	RELITES: {
		INITIAL: "USER.RELITES.INITIAL",
		SUCCESS: "USER.RELITES.SUCCESS",
		FAILED: "USER.RELITES.FAILED"
	}
};

//* main.js
export const LIVE = {
	All: {
		INITIAL: "LIVE.ALL.INITIAL",
		SUCCESS: "LIVE.ALL.SUCCESS",
		FAILED: "LIVE.ALL.FAILED"
	},
	Popular: {
		INITIAL: "LIVE.POPULAR.INITIAL",
		SUCCESS: "LIVE.POPULAR.SUCCESS",
		FAILED: "LIVE.POPULAR.FAILED"
	},
	Following: {
		INITIAL: "LIVE.FOLLOWING.INITIAL",
		SUCCESS: "LIVE.FOLLOWING.SUCCESS",
		FAILED: "LIVE.FOLLOWING.FAILED"
	},
	VIDEOCALL: {
		INITIAL: "LIVE.VIDEOCALL.INITIAL",
		SUCCESS: "LIVE.VIDEOCALL.SUCCESS",
		FAILED: "LIVE.VIDEOCALL.FAILED"
	}
};
export const STREAMING = {
	INITIAL: "STREAMING.INITIAL",
	SUCCESS: "STREAMING.SUCCESS",
	FAILED: "STREAMING.FAILED"
};
export const RELITES = {
	INITIAL: "RELITES.INITIAL",
	SUCCESS: "RELITES.SUCCESS",
	FAILED: "RELITES.FAILED"
};
export const MAIN = {
	IP: "MAIN.IP",
	SEARCH_HASHTAGE: "MAIN.SEARCH_HASHTAGE",
	SEARCH_USERS: "MAIN.SEARCH_USERS",
	SEARCH_LOCATION: "MAIN.SEARCH_LOCATION"
};

//* post.js
export const POST = {
	Latest: {
		INITIAL: "POST.LATEST.INITIAL",
		SUCCESS: "POST.LATEST.SUCCESS",
		FAILED: "POST.LATEST.FAILED"
	},
	Popular: {
		INITIAL: "POST.POPULAR.INITIAL",
		SUCCESS: "POST.POPULAR.SUCCESS",
		FAILED: "POST.POPULAR.FAILED"
	},
	Following: {
		INITIAL: "POST.FOLLOWING.INITIAL",
		SUCCESS: "POST.FOLLOWING.SUCCESS",
		FAILED: "POST.FOLLOWING.FAILED"
	},
	LIKE_UNLIK: "POST.LIKE_UNLIK"
};

//* likes.js
export const LIKES = {
	LIKES: {
		INITIAL: "LIKES.LIKES.INITIAL",
		SUCCESS: "LIKES.LIKES.SUCCESS",
		FAILED: "LIKES.LIKES.FAILED"
	},
	COMMENTS: {
		INITIAL: "LIKES.COMMENTS.INITIAL",
		SUCCESS: "LIKES.COMMENTS.SUCCESS",
		FAILED: "LIKES.COMMENTS.FAILED"
	},
	FAKE_COMMENTS: {
		INITIAL: "LIKES.FAKE_COMMENTS.INITIAL",
		SUCCESS: "LIKES.FAKE_COMMENTS.SUCCESS",
		FAILED: "LIKES.FAKE_COMMENTS.FAILED"
	}
};
//* chat.js
export const CHAT = {
	CHATLIST: {
		INITIAL: "CHAT.CHATLIST.INITIAL",
		SUCCESS: "CHAT.CHATLIST.SUCCESS",
		FAILED: "CHAT.CHATLIST.FAILED"
	},
	MESSAGES: {
		INITIAL: "CHAT.MESSAGES.INITIAL",
		SUCCESS: "CHAT.MESSAGES.SUCCESS",
		APPEND: "CHAT.MESSAGES.APPEND",
		FAILED: "CHAT.MESSAGES.FAILED"
	}
};
